validate helm chart job added
Signed-off-by: Basit Hasan <hasanbasit13@gmail.com>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -43,6 +43,14 @@ jobs:
           path: ~/go/pkg/mod
           key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
           restore-keys: ${{ runner.os }}-go-
+      - name: Validate Helm Chart
+        run: |
+          chart_version=$(yq e '.version' helm/kubedl/Chart.yaml)
+          values_version=$(yq e '.version' helm/kubedl/values.yaml)
+          if [ "$chart_version" != "$values_version" ]; then
+            echo "ERROR: Chart version ($chart_version) does not match values version ($values_version)"
+            exit 1
+
       - name: Run Unit Tests
         run: |
           make generate
